name: Lua Error Report
description: Create a report to help us fix a lua error in the project.
title: "[ERROR]: "
labels:
  - lua error
assignees:
  - McTalian

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a lua error! Please fill out the details below so we can investigate the issue.

  - type: checkboxes
    id: flavor
    attributes:
      label: Game Flavor
      description: Which game flavor(s) does this error occur in? (Check all that you are aware of)
      options:
        - label: Retail
        - label: WoW Classic (Mists of Pandaria)
        - label: Classic Era (Vanilla)
        - label: Classic Era, Season of Discovery
        - label: Classic Era 20th Anniversary (Vanilla)
        - label: Other (please specify in additional information section)
    validations:
      required: true

  - type: checkboxes
    id: locale
    attributes:
      label: Game Locale
      description: Which game locale(s) does this error occur in? (Check all that you are aware of)
      options:
        - label: enUS
        - label: enGB
        - label: deDE
        - label: frFR
        - label: esES
        - label: esMX
        - label: ptBR
        - label: ptPT
        - label: ruRU
        - label: koKR
        - label: zhCN
        - label: zhTW
    validations:
      required: true

  - type: checkboxes
    id: buf-version
    attributes:
      label: BUF Version
      description: Which version of BeaconUnitFrames did you encounter this error?
      options:
        - label: I am using the latest version from CurseForge, Wago, WoWInterface, or GitHub.
        - label: I am using an older version (please specify in additional information section)
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Did this occur when you logged in? When you joined a group? Does it only occur in combat?
      placeholder: |
        1. Customized party frame
        2. Join a party
        3. Party converted to a raid
    validations:
      required: true

  - type: textarea
    id: lua-error
    attributes:
      label: Lua Error
      description: Please paste the lua error that was raised.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Any additional context, game flavors, BeaconUnitFrames version(s), screenshots, etc.
      placeholder: Add any other context about the problem here.
